[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"



[project]
name = "maker-file-index"
version = "0.1.1"
description = "Index maker files (LightBurn first) with thumbnails and notes."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
  { name = "Rich Gibson" }
]
dependencies = [
  "numpy-stl",
  "matplotlib",
  "ezdxf",
]

[project.scripts]
maker-file-index = "maker_file_index.cli:main"
lightburn-extract-notes = "laser_tools.lightburn.extract_notes:main"
lightburn-extract-text  = "laser_tools.lightburn.extract_text:main"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."maker_file_index.plugins"]
lightburn = "maker_file_index.plugins.lightburn:LightBurnPlugin"
stl = "maker_file_index.plugins.stl:STLPlugin"
scad = "maker_file_index.plugins.scad:SCADPlugin"
3mf = "maker_file_index.plugins.three_mf:ThreeMFPlugin"
svg = "maker_file_index.plugins.svg:SVGPlugin"
dxf = "maker_file_index.plugins.dxf:DXFPlugin"
cdr = "maker_file_index.plugins.cdr:CDRPlugin"


